### ISSUE TITLE
Taak: Ontwerp rad maken.

### ISSUE THREAD

**Issue by dreesolivier** [emmaus-6v/2122-6V-Knikkerbaan-groep-6#15]
**Korte beschrijving van je taak**:
Een rad (als een waterrad) ontwerpen en uitprinten.

**Geschatte tijdsduur:** 1 uur

**Comment by bogoedhart** [comment]
![image](https://user-images.githubusercontent.com/57301124/139675417-ba6e8062-6f57-4dd7-a5a2-2289f6367050.jpeg)
