### ISSUE TITLE
Taak: Kleurenscan-doosje ontwerpen/maken

### ISSUE THREAD

**Issue by dreesolivier** [emmaus-6v/2122-6V-Knikkerbaan-groep-6#16]
**Korte beschrijving van je taak**:
Het doosje waar de kleurensensor in moet ontwerpen

**Geschatte tijdsduur:** 2 uur

**Comment by bogoedhart** [comment]
![image](https://user-images.githubusercontent.com/57301124/139673720-693db257-9fad-42d5-97b8-a47ca20921bd.jpeg)

**Comment by bogoedhart** [comment]
Afmetingen sensor
Breedte (2 schroef gaten) 2,5 cm
Lengte 4,3 cm
Gat in linkerkant 1,5 cm vanaf bovenkant
