### ISSUE TITLE
Servo 360 graden werkt niet

### ISSUE THREAD

**Issue by SanneV** [emmaus-6v/2122-6V-Knikkerbaan-groep-6#23]
**Beschrijf de fout**
Ik heb de servo werkende gekregen zodat hij de hele tijd blijft draaien, maar als ik dit kleine stukje code verwerk in de main.ino doet hij het opeens niet meer. In een apart documentje met alleen deze code doet hij het wel. Het aparte documentje heet "servo 360". Ik had het korte stukje dat boven de Setup in de main ook boven de Setup gezet en wat in de Setup hoort in de Setup en wat in de loop hoort in de loop, dus ik snap niet waarom hij nunopeens niet meer draait.

**Hoe te reproduceren?**

1. ...
2. ...
3. ...

Wijs tenslotte deze taak hiernaast toe aan project 'Scrumboard' 👉🏻
(en verwijder deze laatste twee regels uit de beschrijving)

**Comment by cam-emmauscollege** [comment]
ik kan wel schrijven hoe ik denk dat je het in _main.ino moet zetten, maar de kans is groot dat dat is wat jij ook zelf al had gedaan. Heb je voor mijn misschien de code zoals je die in _main.ino zette om de servo te laten werken?

**Comment by SanneV** [comment]
#include <Arduino_JSON.h>
#include <Servo.h>

Servo myservo;


KnikkerPoort poortBoven = KnikkerPoort();
WiFiCommunicator wifi = WiFiCommunicator(WIFI_NETWERK, WIFI_WACHTWOORD, SERVER_DOMEINNAAM);
Teller tellerA = Teller(TELLER_A_PIN);

int serverContactInterval = 15;                // 15 seconden
unsigned long tijdVoorContactMetServer = 0;

void setup() {
  Serial.begin(9600);
  
  poortBoven.begin(BOVEN_POORT_PIN, 0, 90);
  
  wifi.begin();

  //wifi.stuurVerzoek("/api/set/nieuwerun", "");

  poortBoven.open();

  myservo.attach(5);
}


void loop() {
  // laat de teller detecteren:
  tellerA.update();

  
  // pauzeer de knikkerbaan als het tijd is voor contact met server
  if (millis() > tijdVoorContactMetServer && poortBoven.getOpen()) {
    poortBoven.sluit();
  }

  // knikkerbaan is leeggelopen, er zijn geen sensors dit iets moeten meten
  // nu is het tijd om contact te leggen met de server:
  if (millis() > tijdVoorContactMetServer + LEEGLOOP_TIJD) {
    Serial.print("Er zijn nu zoveel knikkers geteld: ");
    Serial.println(tellerA.getAantal());

    tijdVoorContactMetServer = millis() + (unsigned long)serverContactInterval * 1000;
    // en zet nu het poortje weer open:
    poortBoven.open();

    myservo.write(80);
  }
}

dit is de code van de _main als ik de code van de 360 graden servo er in verwerk.

**Comment by SanneV** [comment]
Ik zie al wel dat de teller ook op pin 5 stond maar als ik van de 360 graden servo pin 3 maakt doet hij nog steeds niets.
