### ISSUE TITLE
Thuis aan arduino code

### ISSUE THREAD

**Issue by SanneV** [emmaus-6v/2122-6V-Knikkerbaan-groep-6#24]
**Beschrijf de fout**
Als ik thuis mijn seriele monitor wil openen krijg ik deze error: Board at COM3 is not available
Ik kan hierdoor niet thuis verder met de RGB-sensor.

**Hoe te reproduceren?**

1. ...
2. ...
3. ...

Wijs tenslotte deze taak hiernaast toe aan project 'Scrumboard' 👉🏻
(en verwijder deze laatste twee regels uit de beschrijving)

**Comment by cam-emmauscollege** [comment]
Even voor mijn beeld: heb je al eerder thuis de Arduino werkend gekregen?

**Comment by SanneV** [comment]
Beste meneer Cammeraat,
Ja, want de arduino zelf werkt wel, maar alleen de seriële monitor niet.
Dus ik kan wel met de poortjes werken maar met sensoren gaat het erg lastig
als ik niet weet wat ze waarnemen.

**Comment by cam-emmauscollege** [comment]
Dus je kunt wel code uploaden?
Ik ga even zoeken of ik een oplossing kan vinden. Welk besturingssysteem gebruik je?

In de tussentijd kun je proberen om de Arduino app af te sluiten en opnieuw te starten terwijl je Arduino board ingeplugd is, of je Arduino uit- en in te pluggen zowel met als zonder een 'draaiende' Arduino app. Maar dat heb je misschien ook allemaal al geprobeerd.

Of, andere mogelijkheid: heb je iets anders op pin 0 of 1 aangesloten? Je kunt ook alle draden loshalen en kijken of het dan wel werkt.

**Comment by SanneV** [comment]
Ja ik kan de code wel uploaden. Ik heb windows. Dat in- en uitpluggen had ik gister al geprobeerd. Zelfs als ik de arduino niet verbond kon ik niet de seriële monitor openzetten door de error.

**Comment by cam-emmauscollege** [comment]
Ik ga waarschijnlijk veel dingen aanreiken die je al hebt geprobeerd, maar dit is kan meerdere oorzaken hebben en is een beetje lastig op afstand in één keer op te lossen.

- Het klopt dat je dezelfde fout krijgt als je geen Arduino hebt aangesloten. De seriële monitor kan dan geen verbinding opzetten.

- Heb je in het menu Tools -> Port de juiste poort geselecteerd?
- Heb je je computer al eens opnieuw opgestart?
- Je kon het uploaden dus ik verwacht van wel, maar even voor de zekerheid: je hebt het correcte board geselecteerd? (Arduino Uno Wifi Rev 2)
- Windows heeft een device manager (NL Apparatenbeheer of iets dergelijks). Zie je daar onder USB iets van je Arduino?
- Doet je arduino wel iets anders? Er is geen sprake van kortsluiting op je breadboard?
